version: '1'

services:
  db:
    image: postgres:alpine
    container_name: db-container
    restart: always
    tty: true
    environment:
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_PASSWORD:  ${DB_PASSWORD}
      POSTGRES_DB:  ${DB_DATABASE}
      HOST: ${DB_HOST}
    ports:
      - "5432:5432"
    volumes:
      - db:/var/lib/postgresql/data
  leetcode-app:
    container_name: leetcode-container
    image: leetcode:latest
    tty: true
    build: .
    depends_on:
      - db
    ports:
      - "3000:3000"
volumes:
  db:
